Welcome = """
Willkommen beim Boardgame Night Bot! üé≤
Wir helfen dir dabei, deinen Spieleabend zu organisieren.

Verwendung:
- Nutze /create [Eventname], um ein neues Event zu erstellen.
  Verf√ºgbare Optionen w√§hrend der Erstellung:
    üîí Das Event nur von dir bearbeitbar machen
    üìç Den Veranstaltungsort festlegen
    üë• Einen Button hinzuf√ºgen, der es Nutzern erlaubt teilzunehmen, ohne ein bestimmtes Spiel auszuw√§hlen
- Nutze /add_game [Spielname], um Spiele zum Event hinzuzuf√ºgen.
- Nutze /language [lan], um die Sprache des Bots einzustellen (en/it/de).
- Nutze /location [Ort], um den Standardort des Chats festzulegen oder zu aktualisieren.

Klicke auf die Buttons, um einem Spiel beizutreten oder es zu verlassen.
Viel Spa√ü! üéâ
"""

Usage = "Verwendung: {{.Command}} {{.Example}}"

EventName = "Ereignisname"
GameName = "Spielname"

FailedToCreateEvent = "Ereignis konnte nicht erstellt werden. Bitte versuche es erneut."
FailedToAddGame = "Spiel konnte nicht hinzugef√ºgt werden. Bitte versuche es erneut."
FailedToUpdateMessageEvent = "Nachricht konnte nicht aktualisiert werden. Bitte versuche es erneut."
FailedToUpdateGame = "Spiel konnte nicht aktualisiert werden. Bitte versuche es erneut."
FailedToGetGameInfo = "Spielinformationen von BoardGameGeek konnten nicht abgerufen werden. Bitte versuche es erneut."
FailedToSetLanguage = "Sprache konnte nicht festgelegt werden. Bitte versuche es erneut."
FailedToSetLocation = "Standort konnte nicht festgelegt werden. Bitte versuche es erneut."
FailedToAddPlayer = "Spieler konnte nicht hinzugef√ºgt werden. Bitte versuche es erneut."
FailedToRemovePlayer = "Spieler konnte nicht entfernt werden. Bitte versuche es erneut."
FailedLanguageNotAvailable = "Sprache nicht verf√ºgbar. Bitte versuche es erneut mit einer der folgenden verf√ºgbaren Sprachen: {{.AvailableLanguages}}."
FailedToRegisterWebhook = "Webhook konnte nicht registriert werden. Bitte versuche es erneut. Stelle sicher, dass du einen privaten Chat mit dem Bot hast."
FailedToUnregisterWebhook = "Es ist nicht m√∂glich, die Registrierung des Webhooks zu stornieren. Bitte versuche es erneut."


InvalidNumberOfPlayers = "Ung√ºltige Spieleranzahl. Bitte versuche es erneut."
InvalidBggURL = "Ung√ºltige BoardGameGeek-URL. Bitte versuche es erneut."
InvalidData = "Ung√ºltige Daten. Bitte versuche es erneut."

GameAdded = "Spiel <b>{{.Name}}</b>{{.Link}} hinzugef√ºgt! (1/{{.MaxPlayers}} Spieler).\nAntworte auf diese Nachricht mit der maximalen Spieleranzahl, um sie zu aktualisieren (Standard: {{.MaxPlayers}}).\nDu kannst mir auch den https://boardgamegeek.com/ Link senden, um die Spielinformationen zu aktualisieren.\nKlicke auf den Button, um beizutreten."
GameUpdated = "Spiel aktualisiert!"
LanguageSet = "Sprache auf {{.Language}} gesetzt."
LocationSet = "Standardstandort auf {{.Location}} gesetzt."

GameNotFound = "Spiel nicht gefunden. Du versuchst, die Informationen eines Spiels zu aktualisieren, das nicht existiert. Wahrscheinlich kommentierst du die falsche Nachricht."
EventNotFound = "Ereignis nicht gefunden."
EventLocked = "Ereignis ist gesperrt üîí. Nur der Ersteller kann das Ereignis aktualisieren oder Spiele hinzuf√ºgen."

Join = "Beitreten {{.Name}}"
JoinEvent = "Ereignis beitreten"
UpdatedAt = "<i>Aktualisiert am {{.Time}}</i>\n"
Update = "Aktualisieren"
NotComing = "Nicht teilnehmen"
CreateEventWeb = "Ereignis im Browser erstellen"
AddGame = "Spiel hinzuf√ºgen"
Players = "Spieler"
GameHasBeenDeleted = "Das Spiel {{.Game}} wurde vom Ereignis {{.Event}} von {{.Username}} gel√∂scht."
WebhookRegistered = "Webhook {{.WebhookUrl}} successfully registered."
InvalidWebhookURL = "The webhook URL is not valid. Make sure it starts with http:// or https:// and try again."
WebhookTestSendPrivateMessage = "I verify that I can send you private messages to correctly register the webhook."
WebhookSecret = """Webhook created for chat <b>{{.ChatName}}</b>!

üîë <b>Secret:</b> <code>{{.Secret}}</code>
üåê <b>Webhook:</b>
 <code>{{.WebhookUrl}}</code>
üîó <b>Sie k√∂nnen signierte Anfragen an diese URL senden:</b>
<code>{{.CallbackUrl}}</code>

Keep this secret in a safe place. Use it to validate the HMAC signature of received requests."""
OnlyAdminsCanRegisterWebhook = "Only chat administrators can register a webhook."

Open = "Hier klicken, um die Einstellungen f√ºr Ereignis {{.Name}} zu √∂ffnen und beizutreten."

WebNoParticipants = "Noch keine Teilnehmer."
WebPlayers = "Spieler"
WebJoin = "Beitreten"
WebAddGame = "Spiel hinzuf√ºgen"
WebAddNewGame = "Ein neues Spiel hinzuf√ºgen"
WebWelcome = "Willkommen"
WebGameName = "Spielname"
WebMaxPlayers = "Maximale Spieleranzahl"
WebUpdatedAt = "Aktualisiert am {{.Time}}"
WebUpdateGame = "Spiel aktualisieren"
WebUnlinkFormBoardGameGeek = "Von BoardGameGeek trennen"
WebSomethingWentWrong = "Etwas ist schiefgegangen"
WebDeleteGameConfirmation = "Bist du sicher, dass du das Spiel l√∂schen m√∂chtest?"
WebGameDeletedSuccessfully = "Spiel erfolgreich gel√∂scht"
WebFailedToDeleteGame = "Spiel konnte nicht gel√∂scht werden. Bitte versuche es erneut."
WebDelete = "Spiel l√∂schen"
WebCreateNewEvent = "Ein neues Ereignis erstellen"
WebEventDate = "Ereignisdatum"
WebEventDetails = "Ereignisdetails"
WebEventName = "Ereignisname"
WebEventLocation = "Ereignisort"
WebOnlyAuthorCanAddGames = "Nur der Autor kann Spiele hinzuf√ºgen"
WebAllowAnyoneToJoin = "Erlaube jedem beizutreten, ohne ein Spiel auszuw√§hlen"
WebCreateEvent = "Ereignis erstellen"