Welcome = """
Benvenuto nel Boardgame Night Bot! üé≤
Siamo qui per aiutarti a organizzare la tua serata di giochi da tavolo.

Utilizzo:
- Usa /create [nome evento] per creare un nuovo evento.
  Opzioni disponibili durante la creazione:
    üîí Rendi l'evento modificabile solo da te
    üìç Definisci la location dell'evento
    üë• Aggiungi un bottone per permettere agli utenti di partecipare senza scegliere un gioco
    üïí Specifica l'orario dell'evento formattato come YYYY-MM-DD HH:MM (es. 2023-12-31 20:30)
- Usa /add_game [nome gioco] per aggiungere giochi all'evento.
- Usa /language [lan] per impostare la lingua del bot (en/it/de).
- Usa /location [luogo] per impostare o aggiornare la location usata di default della chat.
- Usa /register [URL] per registrare un webhook.
- Usa /test per inviare un messaggio di test al webhook registrato.

Clicca sui pulsanti per unirti o lasciare un gioco.
Divertiti! üéâ
"""  

Usage = "Utilizzo: {{.Command}} {{.Example}}"

EventName = "nome evento"
GameName = "nome gioco"

FailedToCreateEvent = "Impossibile creare l'evento. Per favore riprova."  
FailedToAddGame = "Impossibile aggiungere il gioco. Per favore riprova."  
FailedToUpdateMessageEvent = "Impossibile aggiornare il messaggio. Per favore riprova."  
FailedToUpdateGame = "Impossibile aggiornare il gioco. Per favore riprova."  
FailedToGetGameInfo = "Impossibile ottenere le informazioni del gioco da BoardGameGeek. Per favore riprova."  
FailedToSetLanguage = "Impostazione della lingua non riuscita. Per favore riprova."
FailedToSetLocation = "Impostazione della posizione non riuscita. Per favore riprova."
FailedToAddPlayer = "Impossibile aggiungere il giocatore. Per favore riprova."  
FailedToRemovePlayer = "Impossibile rimuovere il giocatore. Per favore riprova." 
FailedLanguageNotAvailable = "Lingua non disponibile. Per favore riprova con una di queste lingue disponibili: {{.AvailableLanguages}}."
FailedToRegisterWebhook = "Impossibile registrare il webhook. Per favore riprova. Assicurati di avere una chat privata con il bot."
FailedToUnregisterWebhook = "Impossibile annullare la registrazione del webhook. Per favore riprova."

InvalidNumberOfPlayers = "Numero di giocatori non valido. Per favore riprova."  
InvalidBggURL = "L'URL di BoardGameGeek √® invalido. Per favore riprova."
InvalidData = "Dati non validi. Per favore riprova."

GameAdded = "Gioco <b>{{.Name}}</b>{{.Link}} aggiunto! (1/{{.MaxPlayers}} giocatori).\nRispondi a questo messaggio con il numero massimo di giocatori per aggiornarlo (predefinito {{.MaxPlayers}}).\nPuoi anche inviarmi il link di https://boardgamegeek.com/ per aggiornare le informazioni del gioco.\nClicca sul pulsante per partecipare."
GameUpdated = "Gioco aggiornato!"
LanguageSet = "Lingua impostata su {{.Language}}."
LocationSet = "Posizione predefinita impostata su {{.Location}}."

GameNotFound = "Gioco non trovato. Stai cercando di aggiornare le informazioni di un gioco che non esiste. Probabilmente stai commentando il messaggio sbagliato."  
EventNotFound = "Evento non trovato."
EventLocked = "L'evento √® bloccato üîí. Solo il creatore pu√≤ aggiornare l'evento o aggiungere giochi."

Join = "Partecipa a {{.Name}}"
JoinEvent = "Partecipa all'evento"  
UpdatedAt = "<i>Aggiornato alle {{.Time}}</i>"  
Update = "Aggiorna"
NotComing = "Non partecipo"
CreateEventWeb = "Crea evento dal browser"
AddGame = "Aggiungi un gioco"
Players = "partecipanti"
GameHasBeenDeleted = "Il gioco {{.Game}} √® stato eliminato dall'evento {{.Event}} da {{.Username}}."
WebhookRegistered = "Webhook  {{.WebhookUrl}} registrato con successo."
InvalidWebhookURL = "L'URL del webhook non √® valido. Assicurati che inizi con http:// o https:// e riprova."
WebhookTestSendPrivateMessage = "Verifico di poterti inviare messaggi privati per registrare correttamente il webhook."
WebhookSecret = """Webhook creato per la chat <b>{{.ChatName}}</b>!

üîë <b>Segreto:</b>
<code>{{.Secret}}</code>
üåê <b>Webhook:</b> 
<code>{{.WebhookUrl}}</code>
üîó <b>Puoi inviare richieste firmate a questo URL:</b>
<code>{{.CallbackUrl}}</code>

Conserva questo segreto in un luogo sicuro. Usalo per validare la firma HMAC delle richieste ricevute."""
OnlyAdminsCanRegisterWebhook = "Solo gli amministratori della chat possono registrare un webhook."
WebhookTestDispatched = "Messaggio di test inviato al webhook."

Open = "Premi qui per aprire le impostazioni dell'evento {{.Name}} e partecipare."

WebNoParticipants = "Ancora nessun partecipante."
WebPlayers = "partecipanti"
WebJoin = "Unisciti"
WebAddGame = "Aggiungi un gioco"
WebAddNewGame = "Aggiungi un nuovo gioco"
WebWelcome = "Benvenuto/a"
WebGameName = "Nome del gioco"
WebMaxPlayers = "Giocatori massimi"
WebUpdatedAt = "Aggiornato al {{.Time}}"
WebUpdateGame = "Aggiorna il gioco"
WebUnlinkFormBoardGameGeek = "Scollega da BoardGameGeek"
WebSomethingWentWrong = "Qualcosa √® andato storto"
WebDeleteGameConfirmation = "Sei sicuro di voler eliminare il gioco?"
WebGameDeletedSuccessfully = "Gioco eliminato con successo"
WebFailedToDeleteGame = "Impossibile eliminare il gioco. Per favore riprova."
WebDelete = "Elimina"
WebCreateNewEvent = "Crea un nuovo evento"
WebEventDate = "Data evento"
WebEventDetails = "Dettagli evento"
WebEventName = "Nome evento"
WebEventLocation = "Posizione evento"
WebOnlyAuthorCanAddGames = "Solo l'autore pu√≤ aggiungere giochi"
WebAllowAnyoneToJoin = "Permetti a chiunque di partecipare senza scegliere un gioco"
WebCreateEvent = "Crea evento"