Welcome = """
Welcome to the Boardgame Night Bot! üé≤
We are here to help you organize your board game night.

How to use:
- Use /create [event name] to create a new event.
  Options available during creation:
    üîí Make the event editable only by you
    üìç Set the event location
    üë• Add a button that allows users to participate without choosing a specific game
- Use /add_game [game name] to add games to the event.
- Use /language [lan] to set the bot language (en/it/de).
- Use /location [location] to set or update the default location for the chat.

Click the buttons to join or leave a game.
Have fun! üéâ
"""

Usage = "Usage: {{.Command}} {{.Example}}"

EventName = "event name"
GameName = "game name"

FailedToCreateEvent = "Failed to create event. Please try again."
FailedToAddGame = "Failed to add game. Please try again."
FailedToUpdateMessageEvent = "Failed to update message. Please try again."
FailedToUpdateGame = "Failed to update game. Please try again."
FailedToGetGameInfo = "Failed to get game info from BoardGameGeek. Please try again."
FailedToSetLanguage = "Failed to set language. Please try again."
FailedToSetLocation = "Failed to set location. Please try again."
FailedToAddPlayer = "Failed to add player. Please try again."
FailedToRemovePlayer = "Failed to remove player. Please try again."
FailedLanguageNotAvailable = "Language not available. Please try again with one of these available languages: {{.AvailableLanguages}}."

InvalidNumberOfPlayers = "Invalid number of players. Please try again."
InvalidBggURL = "Invalid BoardGameGeek URL. Please try again."
InvalidData = "Invalid data. Please try again."

GameAdded = "Game <b>{{.Name}}</b>{{.Link}} added! (1/{{.MaxPlayers}} players).\nReply to this message with the max number of player to update (default {{.MaxPlayers}})\nYou can also send me the https://boardgamegeek.com/ link to update the game info.\nClick button to join."
GameUpdated = "Game updated!"
LanguageSet = "Language set to {{.Language}}."
LocationSet = "Default location set to {{.Location}}."

GameNotFound = "Game not found. You are trying to update the information of a game that does not exist. You are probably commenting on the wrong message."
EventNotFound = "Event not found."
EventLocked = "Event is locked üîí. Only the creator can update the event or add games."

Join = "Join {{.Name}}"
JoinEvent = "Join event"
UpdatedAt = "<i>Updated at {{.Time}}</i>"
Update = "Update"
NotComing = "Not coming"
AddGame = "Add a game"
Players = "players"
GameHasBeenDeleted = "The game {{.Game}} has been deleted from the event {{.Event}} by {{.Username}}."

Open = "Click here to open event {{.Name }} settings and join."

WebNoParticipants = "No participants yet."
WebPlayers = "players"
WebJoin = "Join"
WebAddGame = "Add game"
WebAddNewGame = "Add a new game"
WebWelcome = "Welcome"
WebGameName = "Game Name"
WebMaxPlayers = "Max players"
WebUpdatedAt = "Updated at {{.Time}}"
WebUpdateGame = "Update game"
WebUnlinkFormBoardGameGeek = "Unlink from BoardGameGeek"
WebSomethingWentWrong = "Something went wrong"
WebDeleteGameConfirmation = "Are you sure you want to delete the game?"
WebGameDeletedSuccessfully = "Game deleted successfully"
WebFailedToDeleteGame = "Failed to delete game. Please try again."
WebDelete = "Delete"